compressionLevel: 0

enableGlobalCache: true

installStatePath: ./.yarn/root.gz

logFilters:
  - code: YN0005
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - linux
    - darwin

unsafeHttpWhitelist:
  - localhost

yarnPath: ./.yarn/releases/yarn-4.3.0.cjs
