description: 'Reports failures to discord'

parameters:
  template:
    description: |
      Which template to report in discord. Applicable for parallel sandbox jobs
    type: string
    default: 'none'

steps:
  - run:
      when: on_fail
      command: git fetch --unshallow
  - discord/status:
      only_for_branches: main,next,next-release,latest-release
      fail_only: true
      failure_message: $(yarn get-report-message << pipeline.parameters.workflow >> << parameters.template >>)
