import { global } from '@storybook/global';

import { deprecate } from 'storybook/internal/client-logger';

const RUNTIME_MANIFEST_DEPRECATION =
  'The runtime Custom Elements Manifest is deprecated and will be removed in Storybook 12. Set framework.options.customElementsManifest in .storybook/main and enable features.experimentalDocgenServer instead.';

/** @deprecated Use framework.options.customElementsManifest with features.experimentalDocgenServer instead. This runtime manifest helper will be removed in Storybook 12. */
export function isValidComponent(tagName: string): boolean {
  if (!tagName) {
    return false;
  }
  if (typeof tagName === 'string') {
    return true;
  }
  throw new Error('Provided component needs to be a string. e.g. component: "my-element"');
}

/** @deprecated Use framework.options.customElementsManifest with features.experimentalDocgenServer instead. This runtime manifest helper will be removed in Storybook 12. */
export function isValidMetaData(customElements: any): boolean {
  if (!customElements) {
    return false;
  }

  if (
    (customElements.tags && Array.isArray(customElements.tags)) ||
    (customElements.modules && Array.isArray(customElements.modules))
  ) {
    return true;
  }
  throw new Error(
    'You need to set up valid Custom Elements metadata with a manifest generated by @custom-elements-manifest/analyzer. Configure it with framework.options.customElementsManifest in .storybook/main.'
  );
}

/** @deprecated Use framework.options.customElementsManifest with features.experimentalDocgenServer instead. This runtime manifest setter will be removed in Storybook 12. */
export function setCustomElements(customElements: any): void {
  deprecate(`setCustomElements() is deprecated: ${RUNTIME_MANIFEST_DEPRECATION}`);
  global.__STORYBOOK_CUSTOM_ELEMENTS__ = customElements;
}

/** @deprecated Use framework.options.customElementsManifest with features.experimentalDocgenServer instead. This runtime manifest setter will be removed in Storybook 12. */
export function setCustomElementsManifest(customElements: any): void {
  deprecate(`setCustomElementsManifest() is deprecated: ${RUNTIME_MANIFEST_DEPRECATION}`);
  global.__STORYBOOK_CUSTOM_ELEMENTS_MANIFEST__ = customElements;
}

/** @deprecated Use framework.options.customElementsManifest with features.experimentalDocgenServer instead. This runtime manifest getter will be removed in Storybook 12. */
export function getCustomElements(): any {
  return global.__STORYBOOK_CUSTOM_ELEMENTS_MANIFEST__ || global.__STORYBOOK_CUSTOM_ELEMENTS__;
}
