import { existsSync, readFileSync, statSync } from 'node:fs';
import path from 'pathe';
import { logger } from 'storybook/internal/node-logger';

import type { CompodocJson } from './compodocTypes.ts';

const COMPODOC_DEFAULT_PATHS = ['documentation.json', '.compodoc/documentation.json'] as const;

const compodocCache = new Map<string, { mtimeMs: number; json: CompodocJson }>();

/**
 * Find and return the Compodoc JSON generated by the Angular builder.
 *
 * Checks common output locations relative to `cwd`. The Angular builder generates
 * `documentation.json` before Storybook starts when `compodoc: true` is set in `angular.json`.
 *
 * Results are cached per resolved path and validated against the file's `mtimeMs`, so a
 * regenerated `documentation.json` (e.g. after a dev-mode rebuild) is picked up automatically.
 */
export function getCompodocDocumentation({ cwd }: { cwd: string }): CompodocJson | null {
  for (const candidate of COMPODOC_DEFAULT_PATHS) {
    const resolved = path.join(cwd, candidate);
    if (existsSync(resolved)) {
      return readAndCache(resolved);
    }
  }

  logger.warn(
    '[angular:docgen] No Compodoc documentation.json found. ' +
      'Set compodoc: true in your angular.json to enable component documentation.'
  );
  return null;
}

export function invalidateCompodocCache() {
  compodocCache.clear();
}

function readAndCache(filePath: string): CompodocJson | null {
  let mtimeMs: number | undefined;
  try {
    mtimeMs = statSync(filePath).mtimeMs;
  } catch {
    mtimeMs = undefined;
  }

  const cached = compodocCache.get(filePath);
  if (cached && mtimeMs !== undefined && cached.mtimeMs === mtimeMs) {
    return cached.json;
  }

  try {
    const json = JSON.parse(readFileSync(filePath, 'utf-8')) as CompodocJson;
    logger.info(`[angular:docgen] Found Compodoc JSON at ${filePath}`);
    if (mtimeMs !== undefined) {
      compodocCache.set(filePath, { mtimeMs, json });
    }
    return json;
  } catch (err) {
    logger.warn(
      `[angular:docgen] Failed to read Compodoc JSON at "${filePath}": ` +
        `${err instanceof Error ? err.message : String(err)}`
    );
    return null;
  }
}
