import { existsSync, readFileSync } from 'node:fs';
import path from 'pathe';
import { logger } from 'storybook/internal/node-logger';

import type { CompodocJson } from './compodocTypes.ts';

const COMPODOC_DEFAULT_PATHS = ['documentation.json', '.compodoc/documentation.json'] as const;

const compodocCache = new Map<string, CompodocJson>();

/**
 * Find and return the Compodoc JSON generated by the Angular builder.
 *
 * Checks common output locations relative to `cwd`. The Angular builder generates
 * `documentation.json` before Storybook starts when `compodoc: true` is set in `angular.json`.
 *
 * Results are cached so multiple story files in one build share a single lookup.
 */
export function getCompodocDocumentation({ cwd }: { cwd: string }): CompodocJson | null {
  for (const candidate of COMPODOC_DEFAULT_PATHS) {
    const resolved = path.join(cwd, candidate);
    if (existsSync(resolved)) {
      if (compodocCache.has(resolved)) {
        return compodocCache.get(resolved) || null;
      }
      logger.info(`[angular:manifest] Found Compodoc JSON at ${resolved}`);
      return readAndCache(resolved);
    }
  }

  logger.warn(
    '[angular:manifest] No Compodoc documentation.json found. ' +
      'Set compodoc: true in your angular.json to enable component documentation in manifests.'
  );
  return null;
}

export function invalidateCompodocCache() {
  compodocCache.clear();
}

function readAndCache(filePath: string): CompodocJson | null {
  try {
    const json = JSON.parse(readFileSync(filePath, 'utf-8')) as CompodocJson;
    compodocCache.set(filePath, json);
    return json;
  } catch (err) {
    logger.warn(
      `[angular:manifest] Failed to read Compodoc JSON at "${filePath}": ` +
        `${err instanceof Error ? err.message : String(err)}`
    );
    return null;
  }
}
