executor:
  class: xlarge
  name: sb_playwright
parallelism: 2
steps:
  - git-shallow-clone/checkout_advanced:
      clone_options: --depth 1 --verbose
  - attach_workspace:
      at: .
  - run:
      command: |
        cd code
        TEST_FILES=$(circleci tests glob "**/*.{stories}.{ts,tsx,js,jsx,cjs}" | sed "/^e2e-tests\//d" | sed "/^node_modules\//d")
        echo "$TEST_FILES" | circleci tests run --command="xargs yarn test --reporter=junit --reporter=default --outputFile=../test-results/junit-${CIRCLE_NODE_INDEX}.xml" --verbose
      name: Run tests
  - store_test_results:
      path: test-results
  - report-workflow-on-failure
  - cancel-workflow-on-failure
