// auto generated file, do not edit
export type SupportedFrameworks =
  | 'angular'
  | 'ember'
  | 'experimental-nextjs-vite'
  | 'html-vite'
  | 'html-webpack5'
  | 'nextjs'
  | 'preact-vite'
  | 'react-native-web-vite'
  | 'react-vite'
  | 'react-webpack5'
  | 'server-webpack5'
  | 'svelte-vite'
  | 'svelte-webpack5'
  | 'sveltekit'
  | 'vue3-vite'
  | 'web-components-vite'
  | 'web-components-webpack5'
  | 'qwik'
  | 'solid'
  | 'nuxt'
  | 'react-rsbuild'
  | 'vue3-rsbuild';
