installStatePath: ../.yarn/scripts-install-state.gz

logFilters:
  - code: YN0007
    level: discard
  - code: YN0005
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

npmRegistryServer: 'https://registry.yarnpkg.com'

# See https://github.com/nrwl/nx/issues/22177
supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - linux
    - darwin

unsafeHttpWhitelist:
  - localhost
