import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import ansiRegex from 'ansi-regex';
import { Command } from 'commander';
import { execa } from 'execa';
import pc from 'picocolors';

import { ROOT_DIRECTORY, SANDBOX_DIRECTORY } from './utils/constants';

const PORT = process.env.STORYBOOK_SERVE_PORT
  ? Number.parseInt(process.env.STORYBOOK_SERVE_PORT, 10)
  : 6006;

const BUILDER_TO_SANDBOX: Record<string, string> = {
  'builder-vite': 'react-vite/default-ts',
  'builder-webpack5': 'react-webpack/18-ts',
};

const PROVISIONAL_HEADER = [
  '# PROVISIONAL BASELINE — requires reviewer approval before merge',
  '# Generated by: jiti scripts/capture-terminal-output.ts --builder <builder> --mode <mode> --update',
  '#',
  '# To update this baseline after reviewing, run:',
  '#   jiti scripts/capture-terminal-output.ts --builder <builder> --mode <mode> --update',
  '',
].join('\n');

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function normalizeOutput(raw: string, rootDir: string): string {
  const normalizedRoot = rootDir.replace(/\\/g, '/');
  const rootPattern = new RegExp(escapeRegExp(normalizedRoot), 'g');

  return raw
    .replace(rootPattern, '<ROOT>')
    .replace(/\/(?:Users|home|tmp)\/[\w./-]+/g, '<ROOT>')
    .replace(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z/g, '<TIMESTAMP>')
    .replace(/\b\d{2}:\d{2}:\d{2}\b/g, '<TIME>')
    .replace(/localhost:\d+/g, 'localhost:<PORT>')
    .replace(/\b(?:on\s+)?port\s+\d+\b/gi, 'port <PORT>')
    .replace(/\b(?:pid:\s*|PID\s+)\d+\b/g, 'pid: <PID>')
    .replace(
      /\b(?:built in\s*\d+(?:\.\d+)?\s*(?:ms|s)|done in\s*\d+(?:\.\d+)?\s*(?:ms|s)|in\s*\d+(?:\.\d+)?\s*ms)\b/gi,
      'built in <DURATION>'
    )
    .replace(/([./-])[a-f0-9]{6,}(\.[a-z0-9]+\b)/gi, '$1<HASH>$2')
    .replace(/\bheap used:\s*\d+(?:\.\d+)?\s*(?:kB|KB|MB|GB)\b/gi, 'heap used: <MEMORY>')
    .replace(ansiRegex(), '')
    .replace(/\r\n/g, '\n')
    .trimEnd();
}

function createUnifiedDiff(previous: string, next: string): string {
  const beforeLines = previous.split('\n');
  const afterLines = next.split('\n');

  const max = Math.max(beforeLines.length, afterLines.length);
  const diffLines = ['--- baseline', '+++ current', '@@ -1 +1 @@'];

  for (let index = 0; index < max; index += 1) {
    const before = beforeLines[index];
    const after = afterLines[index];

    if (before === after) {
      continue;
    }

    if (before !== undefined) {
      diffLines.push(`-${before}`);
    }

    if (after !== undefined) {
      diffLines.push(`+${after}`);
    }
  }

  return diffLines.join('\n');
}

function buildCommand(mode: 'build' | 'dev'): string {
  if (mode === 'dev') {
    return `yarn storybook --ci --port ${PORT}`;
  }

  return 'yarn build-storybook --quiet';
}

async function main(): Promise<number> {
  const program = new Command();

  program
    .requiredOption('--builder <name>', 'builder target, e.g. builder-vite or builder-webpack5')
    .option('--mode <build|dev>', 'capture mode', 'build')
    .option('--update', 'overwrite snapshot and exit 0', false);

  program.parse(process.argv);

  const options = program.opts<{
    builder: string;
    mode: string;
    update: boolean;
  }>();

  if (options.mode !== 'build' && options.mode !== 'dev') {
    console.error(pc.red(`Invalid mode: ${options.mode}. Allowed values: build, dev`));
    return 1;
  }

  const sandboxKey = BUILDER_TO_SANDBOX[options.builder];

  if (!sandboxKey) {
    console.error(
      pc.red(
        `Unknown builder: ${options.builder}. Supported builders: ${Object.keys(BUILDER_TO_SANDBOX).join(', ')}`
      )
    );
    return 1;
  }

  const mode = options.mode as 'build' | 'dev';
  const command = buildCommand(mode);
  const sandboxDir = join(SANDBOX_DIRECTORY, sandboxKey);
  const currentDir = dirname(fileURLToPath(import.meta.url));
  const snapshotDir = join(currentDir, 'terminal-output-snapshots');
  const snapshotPath = join(snapshotDir, `${options.builder}-${mode}.snap.txt`);

  const result = await execa(command, {
    shell: true,
    all: true,
    reject: false,
    cwd: sandboxDir,
  });

  const rawOutput = result.all ?? '';
  const normalizedOutput = normalizeOutput(rawOutput, ROOT_DIRECTORY);

  await mkdir(snapshotDir, { recursive: true });

  if (options.update) {
    await writeFile(snapshotPath, `${normalizedOutput}\n`, 'utf8');
    console.log(pc.green(`Updated snapshot: ${snapshotPath}`));
    return 0;
  }

  if (!existsSync(snapshotPath)) {
    await writeFile(snapshotPath, `${PROVISIONAL_HEADER}${normalizedOutput}\n`, 'utf8');
    console.log(pc.yellow(`Created provisional baseline: ${snapshotPath}`));
    console.log(
      pc.yellow(
        '⚠️  PROVISIONAL BASELINE — requires reviewer approval before merge. Re-run with --update after review.'
      )
    );
    return 0;
  }

  const baseline = await readFile(snapshotPath, 'utf8');

  if (baseline.trimEnd() === normalizedOutput.trimEnd()) {
    console.log(pc.green(`✅ Output matches baseline: ${snapshotPath}`));
    return 0;
  }

  const diff = createUnifiedDiff(baseline.trimEnd(), normalizedOutput.trimEnd());
  console.log(diff);
  return 1;
}

main()
  .then((exitCode) => process.exit(exitCode))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
