import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { type Template } from '../code/lib/cli-storybook/src/sandbox-templates.ts';
import * as templates from '../code/lib/cli-storybook/src/sandbox-templates.ts';

// @ts-expect-error somehow TS thinks there is a default export
const { allTemplates, merged, daily, normal } = (templates.default ||
  templates) as typeof templates;

// Sandboxes that also run `storybook init` from an empty directory
const INIT_EMPTY_TEMPLATES: Record<string, string> = {
  'react-vite/default-ts': 'react-vite-ts',
  'nextjs/default-ts': 'nextjs-ts',
  'vue3-vite/default-ts': 'vue-vite-ts',
  'lit-vite/default-ts': 'lit-vite-ts',
};

const projectJson = (
  name: string,
  framework: string | undefined,
  tags: string[],
  template: Template
) => ({
  name,
  description: 'Do not edit. Auto generated by scripts/create-nx-sandbox-projects.ts.',
  projectType: 'application',
  implicitDependencies: [
    'core',
    'cli',
    'addon-a11y',
    'addon-docs',
    'addon-vitest',
    'addon-onboarding',
    ...(framework ? [framework] : []),
  ],
  targets: {
    sandbox: {
      options: {
        // Ensure Nx sandboxes write to a stable, slash-free folder name
        // e.g. "react-vite/default-ts" -> "react-vite-default-ts"
        dir: name.replaceAll('/', '-'),
      },
    },
    dev: {},
    ...(template.typeCheck === true
      ? {
          'check-sandbox': {},
        }
      : {}),
    ...(template.skipTasks && template.skipTasks.includes('vitest-integration')
      ? {}
      : {
          'vitest-integration': {},
        }),
    build: {
      options: {
        dir: name.replaceAll('/', '-'),
      },
    },
    chromatic: {},
    serve: {},
    ...(template.skipTasks && template.skipTasks.includes('e2e-tests')
      ? {}
      : {
          'e2e-tests': {},
        }),
    ...(template.skipTasks && template.skipTasks.includes('e2e-tests-dev')
      ? {}
      : {
          'e2e-tests-dev': {},
        }),
    ...(template.skipTasks && template.skipTasks.includes('test-runner')
      ? {}
      : {
          'test-runner': {},
        }),
    ...(template.skipTasks && template.skipTasks.includes('test-runner-dev')
      ? {}
      : {
          'test-runner-dev': {},
        }),
    ...(name in INIT_EMPTY_TEMPLATES
      ? {
          'init-empty': {
            options: { env: { STORYBOOK_INIT_EMPTY_TYPE: INIT_EMPTY_TEMPLATES[name] } },
          },
        }
      : {}),
    ...(name === 'react-vite/default-ts'
      ? {
          'init-features': {
            options: { env: { STORYBOOK_INIT_EMPTY_TYPE: 'react-vite-ts' } },
          },
        }
      : {}),
  },
  tags,
});
await Promise.all(
  Object.entries(allTemplates).map(async ([key, value]) => {
    const p = key.replaceAll('/', '-');
    const full = join(process.cwd(), '../code/sandbox', p, 'project.json');

    console.log(full);
    const framework = value.expected.framework;
    const project = framework.includes('@storybook/')
      ? framework.replace('@storybook/', '')
      : undefined;
    console.log(project);
    console.log();
    const isInitEmpty = key in INIT_EMPTY_TEMPLATES;
    const isReactViteDefault = key === 'react-vite/default-ts';

    const tags = [
      ...(normal.includes(key as any) && !value.inDevelopment ? ['ci:normal'] : []),
      ...(merged.includes(key as any) && !value.inDevelopment ? ['ci:merged'] : []),
      ...(daily.includes(key as any) && !value.inDevelopment ? ['ci:daily'] : []),
      // Windows CI uses the first sandbox (react-vite/default-ts)
      ...(isReactViteDefault ? ['ci:windows'] : []),
      // init-empty cadence (mirrors scripts/ci/init-empty.ts getInitEmpty()):
      //   react-vite/default-ts: normal+, merged+, daily+
      //   nextjs/default-ts, vue3-vite/default-ts, lit-vite/default-ts: merged+, daily+
      ...(isReactViteDefault ? ['ci:init-empty-normal'] : []),
      ...(isInitEmpty ? ['ci:init-empty-merged', 'ci:init-empty-daily'] : []),
      // init-features: only react-vite/default-ts, all tiers (mirrors defineEmptyInitFeatures)
      ...(isReactViteDefault ? ['ci:init-features'] : []),
      // test-runner: only react-vite/default-ts, only daily (mirrors
      // CircleCI's defineSandboxTestRunner emitted as first-template daily extra)
      ...(isReactViteDefault ? ['ci:test-runner-daily'] : []),
    ];
    ensureDirectoryExistence(full);
    console.log(full);

    const data = JSON.stringify(projectJson(key, project, tags, value), null, 2) + '\n';

    writeFileSync(full, data, { encoding: 'utf-8' });
  })
);

function ensureDirectoryExistence(filePath: string): void {
  const dir = dirname(filePath);
  if (existsSync(dir)) {
    return;
  }
  ensureDirectoryExistence(dir);
  mkdirSync(dir);
}
