import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { type Template } from '../code/lib/cli-storybook/src/sandbox-templates.ts';
import * as templates from '../code/lib/cli-storybook/src/sandbox-templates.ts';

// @ts-expect-error somehow TS thinks there is a default export
const { allTemplates, merged, daily, normal } = (templates.default ||
  templates) as typeof templates;

const projectJson = (
  name: string,
  framework: string | undefined,
  tags: string[],
  template: Template
) => ({
  name,
  description: 'Do not edit. Auto generated by scripts/create-nx-sandbox-projects.ts.',
  projectType: 'application',
  implicitDependencies: [
    'core',
    'cli',
    'addon-a11y',
    'addon-docs',
    'addon-vitest',
    'addon-onboarding',
    ...(framework ? [framework] : []),
  ],
  targets: {
    sandbox: {
      options: {
        // Ensure Nx sandboxes write to a stable, slash-free folder name
        // e.g. "react-vite/default-ts" -> "react-vite-default-ts"
        dir: name.replaceAll('/', '-'),
      },
    },
    dev: {},
    ...(template.typeCheck === true
      ? {
          'check-sandbox': {},
        }
      : {}),
    ...(template.skipTasks && template.skipTasks.includes('vitest-integration')
      ? {}
      : {
          'vitest-integration': {},
        }),
    build: {
      options: {
        dir: name.replaceAll('/', '-'),
      },
    },
    ...(template.skipTasks && template.skipTasks.includes('chromatic')
      ? {}
      : {
          chromatic: {},
        }),
    serve: {},
    ...(template.skipTasks && template.skipTasks.includes('e2e-tests')
      ? {}
      : {
          'e2e-tests': {},
        }),
    ...(template.skipTasks && template.skipTasks.includes('e2e-tests-dev')
      ? {}
      : {
          'e2e-tests-dev': {},
        }),
    // Note: init-empty / init-features / test-runner are NOT emitted per-sandbox here.
    // They live on dedicated virtual projects in test-storybooks/ci-jobs/* so that a
    // single `nx run-many` per tier selects them with the right cadence via tags.
  },
  tags,
});
await Promise.all(
  Object.entries(allTemplates).map(async ([key, value]) => {
    const p = key.replaceAll('/', '-');
    const full = join(process.cwd(), '../code/sandbox', p, 'project.json');

    console.log(full);
    const framework = value.expected.framework;
    const project = framework.includes('@storybook/')
      ? framework.replace('@storybook/', '')
      : undefined;
    console.log(project);
    console.log();
    const tags = [
      ...(normal.includes(key as any) && !value.inDevelopment ? ['ci:normal'] : []),
      ...(merged.includes(key as any) && !value.inDevelopment ? ['ci:merged'] : []),
      ...(daily.includes(key as any) && !value.inDevelopment ? ['ci:daily'] : []),
      // Windows CI uses the first sandbox (react-vite/default-ts)
      ...(key === 'react-vite/default-ts' ? ['ci:windows'] : []),
    ];
    ensureDirectoryExistence(full);
    console.log(full);

    const data = JSON.stringify(projectJson(key, project, tags, value), null, 2) + '\n';

    writeFileSync(full, data, { encoding: 'utf-8' });
  })
);

function ensureDirectoryExistence(filePath: string): void {
  const dir = dirname(filePath);
  if (existsSync(dir)) {
    return;
  }
  ensureDirectoryExistence(dir);
  mkdirSync(dir);
}

// Apply oxfmt so generated files match the repo format rules (e.g. short arrays on one line)
try {
  execSync('yarn fmt:write code/sandbox', {
    cwd: join(process.cwd(), '..'),
    stdio: 'inherit',
  });
} catch (err) {
  console.warn('oxfmt pass failed or not available; sandbox JSON may need manual formatting.');
}
