on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - edited
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

name: Danger JS
jobs:
  dangerJS:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Checkout our own base code, NOT the untrusted PR code.
          ref: ${{ github.event.pull_request.base.sha }}
          persist-credentials: false
      - name: Danger JS
        uses: docker://ghcr.io/danger/danger-js:13.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --dangerfile scripts/dangerfile.js
