name: Fork checks

on:
  push:
    branches:
      - next
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  # This job is only for forks, so they can get basic checks in without a CircleCI API key
  check:
    name: Core Type Checking
    if: github.repository_owner != 'storybookjs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install
        with:
          install-code-deps: true

      - name: check
        run: yarn task --task check

  # This job is only for forks, so they can get basic checks in without a CircleCI API key
  prettier:
    name: Core Formatting
    if: github.repository_owner != 'storybookjs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install
        with:
          install-code-deps: true

      - name: prettier
        run: cd code && yarn lint:prettier --check .
