name: Trigger CircleCI workflow

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-and-install

      - name: run compile
        run: yarn task --task=compile --start-from=compile --no-link
      - name: run compile
        run: yarn task --task=compile --start-from=compile --no-link
      - name: run compile
        run: yarn task --task=compile --start-from=compile --no-link
      - name: run compile
        run: yarn task --task=compile --start-from=compile --no-link
